SELECT *
FROM
XXQIA_FIN_INV_TRACKING_V
WHERE 
(
(
PERSON_ID in (SELECT PERSON_ID FROM EMPLOYEE_LIST_V where USER_NAME_CODE LIKE '%'|| UPPER (:P_PERSON_ID) || '%' OR :P_PERSON_ID IS NULL)
) 
OR
(
PERSON_ID in (SELECT PERSON_ID FROM EMPLOYEE_LIST_V where UPPER(USER_NAME_CODE) LIKE  UPPER(DECODE(:P_PERSON_ID, 'Search', USER_NAME_CODE, NULL, USER_NAME_CODE )) OR UPPER(:P_PERSON_ID)= UPPER('undefined'))
) 	
)
and 
((UPPER (INVOICE_NO) LIKE '%'|| UPPER (:P_INVOICE_NO) || '%' OR :P_INVOICE_NO IS NULL) 
OR UPPER(:P_INVOICE_NO) = UPPER('Search') OR UPPER(:P_INVOICE_NO)= UPPER('undefined'))
and 
((UPPER (PO_NUMBER) LIKE '%'|| UPPER (:P_PO_NUMBER) || '%' OR :P_PO_NUMBER IS NULL) 
OR UPPER(:P_PO_NUMBER) = UPPER('Search') OR UPPER(:P_PO_NUMBER)= UPPER('undefined'))
and 
((UPPER (STATUS) LIKE '%'|| UPPER (:P_STATUS) || '%' OR :P_STATUS IS NULL) 
OR UPPER(:P_STATUS) = UPPER('Search') OR UPPER(:P_STATUS)= UPPER('undefined'))
and 
((UPPER (VENDOR_NAME) LIKE '%'|| UPPER (:P_VENDOR_NAME) || '%' OR :P_VENDOR_NAME IS NULL) 
OR UPPER(:P_VENDOR_NAME) = UPPER('Search') OR UPPER(:P_VENDOR_NAME)= UPPER('undefined'))
and 
((UPPER (DEPARTMENT) LIKE '%'|| UPPER (:P_DEPARTMENT) || '%' OR :P_DEPARTMENT IS NULL) 
OR UPPER(:P_DEPARTMENT) = UPPER('Search') OR UPPER(:P_DEPARTMENT)= UPPER('undefined'))
and 
((UPPER (INVOICE_REQUEST_NO) LIKE '%'|| UPPER (:P_INVOICE_REQUEST_NO) || '%' OR :P_INVOICE_REQUEST_NO IS NULL) 
OR UPPER(:P_INVOICE_REQUEST_NO) = UPPER('Search') OR UPPER(:P_INVOICE_REQUEST_NO)= UPPER('undefined'))
